FROM mcr.microsoft.com/dotnet/core/runtime:3.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build
WORKDIR /src
COPY ["ASPCoreWithAngular.csproj", "./"]
RUN dotnet restore "./ASPCoreWithAngular.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "ASPCoreWithAngular.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ASPCoreWithAngular.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ASPCoreWithAngular.dll"]
